# Generated by Django 4.1.3 on 2024-07-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermgmtapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default='bio', max_length=500),
            preserve_default=False,
        ),
    ]
