# Generated by Django 4.1.3 on 2024-07-13 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermgmtapi', '0005_rename_image_post_image_url_rename_tag_post_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(related_name='posts', through='watermgmtapi.PostTag', to='watermgmtapi.tag'),
        ),
    ]
