# Generated by Django 5.0.7 on 2024-07-15 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watermgmtapi', '0006_remove_post_tags_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(to='watermgmtapi.like'),
        ),
    ]
